### ISSUE TITLE
Example pcap

### ISSUE THREAD

**Issue by iXanthos** [ahlashkari/ALFlowLyzer#120]
Hello,

no matter which pcap I am using, I cannot make the tool to create flows. The result is an empty .csv file. I am using pcaps from https://www.unb.ca/cic/datasets/ddos-2019.html, specifically the SAT-01-12-2018_0240. There is no error output. If I use https://github.com/ahlashkari/NTLFlowLyzer with the same hyperparameters in the config, I get a result. Is this a bug or am I doing something wrong?

Regards,
Iordanis

**Comment by moein-shafi** [comment]
Given this clarification, I'll proceed to close this particular issue. However, please don't hesitate to reconnect if you encounter any further difficulties or have additional inquiries. Your feedback is invaluable to us as we strive to maintain the integrity and functionality of ALFlowLyzer.
